import { randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import { expect, test } from "@playwright/test";
import { createOTP } from "@better-auth/utils/otp";
import { base32 } from "@better-auth/utils/base32";

let scope: string;
let password: string;
function fixture(action: "prepare" | "cleanup") {
  execFileSync(process.execPath, ["--env-file=.env", "--conditions=react-server", "--import", "tsx", "tests/e2e/account-fixtures.ts"], { input: JSON.stringify({ action, scope, password }), stdio: ["pipe", "pipe", "pipe"] });
}
test.beforeEach(async ({ page }) => {
  scope = `e2e-account-${randomUUID()}`; password = `E2E-${randomUUID()}`;
  fixture("prepare");
  await page.setExtraHTTPHeaders({ "x-forwarded-for": `10.210.${Math.floor(Math.random() * 250)}.${Math.floor(Math.random() * 250) + 1}` });
});
test.afterEach(() => fixture("cleanup"));

test("cliente: registro, direcciones, compra propia y cierre de sesión", async ({ page, browser }) => {
  test.setTimeout(90_000);
  await page.goto("/cuenta/registro");
  await page.getByLabel("Nombre completo", { exact: true }).fill("Ana Prueba");
  await page.getByLabel("Correo electrónico", { exact: true }).fill(`${scope}-customer@example.com`);
  await page.getByLabel("Contraseña", { exact: true }).fill(password);
  await page.getByLabel("Repetir contraseña", { exact: true }).fill(password);
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Crear cuenta", exact: true }).click();
  await expect(page).toHaveURL(/\/cuenta$/);
  await page.getByLabel("Nombre", { exact: true }).fill("Ana");
  await page.getByLabel("Apellido", { exact: true }).fill("Prueba");
  await page.getByLabel("Teléfono", { exact: true }).fill("+56912345678");
  await page.getByLabel("RUT", { exact: true }).fill("11111111-1");
  await page.getByRole("button", { name: "Guardar cambios" }).click();
  await expect(page.getByText("Cambios guardados.")).toBeVisible();
  await page.getByRole("link", { name: "Mis direcciones" }).click();
  await page.getByRole("button", { name: "Agregar dirección" }).click();
  await page.getByLabel("Nombre completo", { exact: true }).fill("Ana Prueba");
  await page.getByLabel("Teléfono", { exact: true }).fill("+56912345678");
  await page.getByLabel("Región", { exact: true }).selectOption("Región de Los Lagos");
  await page.getByLabel("Comuna", { exact: true }).selectOption("Castro");
  await page.getByLabel("Calle", { exact: true }).fill("Calle de prueba");
  await page.getByLabel("Número", { exact: true }).fill("123");
  await page.getByRole("button", { name: "Guardar cambios" }).click();
  await expect(page.getByText("Dirección principal")).toBeVisible();
  await page.goto(`/producto/${scope}`);
  await page.getByRole("button", { name: /Agregar al carrito/ }).click();
  await expect(page.getByText("Agregado al carrito")).toBeVisible();
  await page.goto("/checkout");
  await expect(page.getByLabel("Email", { exact: true })).toHaveValue(`${scope}-customer@example.com`);
  await expect(page.getByLabel("Nombre", { exact: true })).toHaveValue("Ana");
  await page.getByRole("button", { name: /^Retiro/ }).click();
  await page.getByRole("checkbox", { name: /Acepto los términos/i }).check();
  await page.getByRole("button", { name: /Continuar al pago/ }).click();
  await expect(page).toHaveURL(/\/checkout\/pago\/TG-\d+/);
  const number = page.url().split("/").pop()!;
  await expect(page.getByRole("heading", { name: number, exact: true })).toBeVisible();
  await page.goto("/cuenta/pedidos");
  await expect(page.getByRole("link", { name: number, exact: true })).toBeVisible();
  await page.getByRole("link", { name: number, exact: true }).click();
  await expect(page.getByText("Producto de prueba de cuenta")).toBeVisible();
  const stranger = await browser.newContext();
  const response = await stranger.request.get(page.url().replace("/cuenta/pedidos/", "/checkout/pago/"));
  expect(response.status()).toBe(404);
  await stranger.close();
  await page.goto("/admin/productos");
  await expect(page).toHaveURL(/\/admin\/login/);
  await page.goto("/cuenta");
  await page.getByRole("button", { name: "Cerrar sesión", exact: true }).click();
  await expect(page).toHaveURL(/\/cuenta\/login/);
  await page.goto("/cuenta/pedidos");
  await expect(page).toHaveURL(/\/cuenta\/login/);
  await page.getByLabel("Correo electrónico", { exact: true }).fill(`${scope}-customer@example.com`);
  await page.getByLabel("Contraseña", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Iniciar sesión", exact: true }).click();
  await expect(page).toHaveURL(/\/cuenta$/);
});

test("invitado: conserva el checkout y protege la página de pago", async ({ page, browser }) => {
  test.setTimeout(60_000);
  await page.goto(`/producto/${scope}`);
  await page.getByRole("button", { name: /Agregar al carrito/ }).click();
  await expect(page.getByText("Agregado al carrito")).toBeVisible();
  await page.goto("/checkout");
  await page.getByLabel("Nombre", { exact: true }).fill("Invitada");
  await page.getByLabel("Apellido", { exact: true }).fill("Prueba");
  await page.getByLabel("RUT", { exact: true }).fill("11111111-1");
  await page.getByLabel("Teléfono", { exact: true }).fill("+56912345678");
  await page.getByLabel("Email", { exact: true }).fill(`${scope}-guest@example.com`);
  await page.getByRole("button", { name: /^Retiro/ }).click();
  await page.getByRole("checkbox", { name: /Acepto los términos/i }).check();
  await page.getByRole("button", { name: /Continuar al pago/ }).click();
  await expect(page).toHaveURL(/\/checkout\/pago\/TG-\d+/);
  await expect(page.getByRole("heading", { name: /TG-\d+/ })).toBeVisible();
  const stranger = await browser.newContext();
  expect((await stranger.request.get(page.url())).status()).toBe(404);
  await stranger.close();
});

test("administrador: login, equipo, contraseña y segundo factor", async ({ page }) => {
  test.setTimeout(90_000);
  await page.goto("/admin/login");
  await page.getByLabel("Correo electrónico", { exact: true }).fill(`${scope}-owner@example.com`);
  await page.getByLabel("Contraseña", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Iniciar sesión", exact: true }).click();
  await expect(page).toHaveURL(/\/admin$/);
  await page.goto("/admin/equipo");
  await page.getByLabel("Nombre completo", { exact: true }).fill("Staff E2E");
  await page.getByLabel("Correo electrónico", { exact: true }).fill(`${scope}-staff@example.com`);
  await page.getByLabel("Contraseña", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Crear acceso de personal", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Staff E2E" })).toBeVisible();
  await page.goto("/admin/seguridad");
  await page.getByLabel("Contraseña actual", { exact: true }).first().fill(password);
  await page.getByLabel("Nueva contraseña", { exact: true }).fill(`${password}-new`);
  await page.getByLabel("Repetir contraseña", { exact: true }).fill(`${password}-new`);
  await page.getByRole("button", { name: "Cambiar contraseña", exact: true }).click();
  await expect(page.getByText("Contraseña actualizada. Se cerraron las otras sesiones.")).toBeVisible();
  await page.getByLabel("Contraseña actual", { exact: true }).last().fill(`${password}-new`);
  await page.getByRole("button", { name: "Activar verificación en dos pasos", exact: true }).click();
  const secretText = await page.locator("code").textContent();
  const secret = new TextDecoder().decode(base32.decode(secretText!));
  await page.getByLabel("Código de verificación", { exact: true }).fill(await createOTP(secret).totp());
  await page.getByRole("button", { name: "Confirmar código", exact: true }).click();
  await expect(page.getByText("Verificación en dos pasos activada.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Salir", exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/login/);
  await page.getByLabel("Correo electrónico", { exact: true }).fill(`${scope}-owner@example.com`);
  await page.getByLabel("Contraseña", { exact: true }).fill(`${password}-new`);
  await page.getByRole("button", { name: "Iniciar sesión", exact: true }).click();
  await page.getByLabel("Código de verificación", { exact: true }).fill(await createOTP(secret).totp());
  await page.getByRole("button", { name: "Confirmar código", exact: true }).click();
  await expect(page).toHaveURL(/\/admin$/);
});
