ALTER TYPE "ProductReviewStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "ProductReviewStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "ProductReviewStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
